- job:
    name: zaqar-grenade-base
    parent: legacy-dsvm-base
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/python-zaqarclient
      - openstack/zaqar
      - openstack/zaqar-tempest-plugin
    run: playbooks/legacy/grenade-devstack-zaqar-base/run.yaml
    post-run: playbooks/legacy/grenade-devstack-zaqar-base/post.yaml
    timeout: 7800

- job:
    name: zaqar-grenade-mongodb
    parent: zaqar-grenade-base
    voting: false
    vars:
      database_backend: mongodb

- job:
    name: zaqar-grenade-redis
    parent: zaqar-grenade-base
    voting: false
    vars:
      database_backend: redis

- job:
    name: zaqar-grenade-swift
    parent: zaqar-grenade-base
    voting: false
    vars:
      database_backend: swift

- job:
    name: zaqar-tox-integration
    parent: openstack-tox
    description: |
      Run Zaqar integration tests using tox with environment ``integration``.
    vars:
      tox_envlist: integration

- job:
    name: zaqar-rally
    parent: rally-task-zaqar
    vars:
      rally_task: rally-jobs/zaqar-zaqar.yaml

- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - zaqar-tox-integration
        - zaqar-tempest-plugin-mongodb
        - zaqar-tempest-plugin-redis
        - zaqar-tempest-plugin-swift
        - zaqar-tempest-plugin-swift-ipv6
        - zaqar-grenade-mongodb
        - zaqar-grenade-redis
        - zaqar-grenade-swift
        # TripleO jobs that deploy Zaqar.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - tripleo-ci-centos-7-scenario002-standalone
        # Heat job that deploy Zaqar
        - heat-functional-convg-mysql-lbaasv2
        - zaqar-rally:
            voting: false
    gate:
      queue: zaqar
      jobs:
        - zaqar-tox-integration
        - zaqar-tempest-plugin-mongodb
        - zaqar-tempest-plugin-redis
        - zaqar-tempest-plugin-swift
        - zaqar-tempest-plugin-swift-ipv6
        - tripleo-ci-centos-7-scenario002-standalone
        - heat-functional-convg-mysql-lbaasv2
